### ISSUE TITLE
Wrong time when host is set to german time zone

### ISSUE THREAD

**Issue by JasperPecher** [Nisbo/another_mvg#1]
I had an issue with your awesome integration that I was only shown the departures in one hour. This happened with Home Assistant as a Docker container, if you already give the container the german time zone or if I host Home Assistant as a Proxmox VM.
My solution was to remove the timezone conversion in your code for dt_object and dt_objectReal
dt_object = self.convert_datetime_timezone(datetime.fromtimestamp(timestampPlannedDeparture), "UTC", DEFAULT_TIMEZONE)
-->
dt_object = datetime.fromtimestamp(timestampPlannedDeparture)

Now I have the correct times in my dashboard.
Thank you for this wonderful integration!

**Comment by Nisbo** [comment]
I was already working on a version, where you can define the time zones, because I had the same issue after moving from my Synology/Docker installation running with UTC settings to a NUC installation with HAOS.

Now I released a new version, where you can set the time zone in the configuration.yaml.
Default is "Europe/Berlin". So I assume, in your case you don't need to configure anything.
