### ISSUE TITLE
sensor 'another_mvg' not found

### ISSUE THREAD

**Issue by Gridomin** [Nisbo/another_mvg#5]
Hi,
i am getting an error when checking the configuration.yaml with the dev-tools:

Platform error 'sensor' from integration 'another_mvg' - Integration 'another_mvg' not found.

After restarting HA, the sensor can not be found.
Checking with studio code server, i am getting 1 error in the manifest.json in another_mvg: 
"expected a JSON objekt, array or literal". On Line 7 (!DOCTYPE)
There seem to be errors in the content-cards a well ("1000 problems in this file"), also starting with the doctype-error.

I would appreciate your help. Thank you!!

My configuration-yaml looks like this:

default_config:

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.1

camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    country: "de"
    draw: ['all']
    auto_update: true
    scan_interval:
      seconds: 600 #10minutes
    attributes:
      - calibration_points

template:
  - sensor:
      - name: "Stromzähler Verbrauch"
        unique_id: "StromVerbrauch"
        unit_of_measurement: 'kWh'
        device_class: "energy"
        state_class: "total_increasing"
        state: >-
            {{ float(states('sensor.tasmota_ace3000_total_inz1')) | round(3) }}
  - sensor:
      - name: "Stromzähler Erzeugung"
        unique_id: "StromErzeugung"
        unit_of_measurement: 'kWh'
        device_class: "energy"
        state_class: "total_increasing"
        state: >-
            {{ float(states('sensor.tasmota_ace3000_total_exz1')) | round(3) }}

sensor:
  - platform: another_mvg
    name: "Schulstraße"
    globalid: "de:09179:6303"

**Comment by Nisbo** [comment]
Sorry for the late answer.

I am not familar with "studio code server" and dont know what this is. I am assume that its a part of Visual Studio, however I am also not familar with this program. 

Line 7 of manifest.json 
```"iot_class": "local_polling",```
dont know why the program is expecting a doctype in this line.

I assume there was a transfer error to your HA server.

> Platform error 'sensor' from integration 'another_mvg' - Integration 'another_mvg' not found.

This is a clear error, HA was not able to find "another_mvg" in your **custom_components** folder.
Make sure that the folder ```another_mvg``` (and all files) are inside the folder
```custom_components```

your yaml code is not correct, or it is malformatted in this post.

```
sensor:
  - platform: another_mvg
    name: "Schulstraße"
    globalid: "de:09179:6303"
```
But I think its only the formatting here, because HA was not able to find the sensor and not complaining about a wrong yaml, so your yaml code should be correct.

I assume something was not transferred correct. How did you transfer the files ?
Can you use the HomeAssistant File Editor to check the content of the files ? And maybe replace the content of the files with the RAW Code from github via the file Editor.

![grafik](https://github.com/Nisbo/another_mvg/assets/26260572/c5040deb-a598-4918-9253-7b1f2b97ada8)

If you have to use the Config Editor Addon (because you are not running HA OS) it should look like this

![grafik](https://github.com/Nisbo/another_mvg/assets/26260572/fbd10208-306b-41ab-aa50-155549914ed3)

**Comment by Gridomin** [comment]
Thank you!
There was indeed an error with uploading the files. I had to manuel copy&paste the text inside the files to my versions in HA. I then finally did get the sensor working.
Then I had the problem, that the custom-card was not recognized, but after reloading HA with ctrl-F5, they also finally worked.

Now I have the custom-card (using "small"-version) with my working sensor on the dashboard, but it is not readable, because the font color is black:
![image](https://github.com/Nisbo/another_mvg/assets/101142520/d2cbcae2-048d-44a5-9da1-cee08afdb5e3)

**Comment by Nisbo** [comment]
ersetze in der **content-card-another-mvg.js** mal das

```
        .destination {
          width: 60%;
          text-wrap: wrap;
        }
        .track {
          padding: 0 5px;
          width: fit-content;
        }
        .time {
          padding-right: 5px;
          width: fit-content;
          white-space: nowrap;
        }
```

durch:

```
        .destination {
          width: 60%;
          text-wrap: wrap;
          color: #FFFFFF;
        }
        .track {
          padding: 0 5px;
          width: fit-content;
          color: #FFFFFF;
        }
        .time {
          padding-right: 5px;
          width: fit-content;
          white-space: nowrap;
          color: #FFFFFF;
        }
```

und dann das
```
        /* Name of the card - from name parameter */
        .cardname {
          font-weight: bold;
          font-size:1.0em;
          padding: 2px 0 2px 8px;
        }
```

durch das
```
        /* Name of the card - from name parameter */
        .cardname {
          font-weight: bold;
          font-size:1.0em;
          padding: 2px 0 2px 8px;
          color: #FFFFFF;
        }
```


also jeweils ```color: #FFFFFF;``` hinzufügen.
Danach dann das Frontend wieder neu laden.

**Comment by Gridomin** [comment]
Viel Besser. Herzlichen Dank für deine ganze Unterstützung!
