### ISSUE TITLE
Custom element not found: content-card-another-mvg

### ISSUE THREAD

**Issue by yakko2001** [Nisbo/another_mvg#8]
Always get the message "Custom element not found: content-card-another-mvg" on my custom card.

- I already added the ressource URL: "/local/content-card-another-mvg.js"
- I also added the folder and all files to "homeassistent/custom_components/another_mvg/"
- I'm using HACS

Any Ideas?
Thank you in advanced.

**Comment by Nisbo** [comment]
Regarding this error message, it looks like the file is missing. This was a separate step in the manual and the file is not located in the ***another_mvg*** folder.

I assume that you restarted HA after installing the addon and cleared your frontend cache. I also assume that you added the resource as JavaScript.

To check if the file is in the correct folder, try to open it in your browser. I recommend to use your PC instead of the smart phone browser.

```http://192.168.178.52:8123/local/content-card-another-mvg.js```
replace ```192.168.178.52``` with the IP of your HA server. If you changed the standard port ```8123``` you also have to change this in the url.

If you get an 404 error, make sure the ```content-card-another-mvg.js``` is in the correct folder.
It has to be in the ```www``` folder. This folder is located in the same folder than your ```configuration.yaml```

![grafik](https://github.com/Nisbo/another_mvg/assets/26260572/08cca27a-c7d5-469e-814b-173e4802f101)
